<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\SalesDashboard.Contracts\SalesDashboard.Contracts.csproj" />
    <ProjectReference Include="..\Modules\SalesDashboard.Modules.Sales\SalesDashboard.Modules.Sales.csproj" />
    <ProjectReference Include="..\Modules\SalesDashboard.Modules.Catalog\SalesDashboard.Modules.Catalog.csproj" />
    <ProjectReference Include="..\Modules\SalesDashboard.Modules.People\SalesDashboard.Modules.People.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Dapper" Version="2.1.79" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.11">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.3" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
